import { Router } from 'express';
import { prisma } from '../lib/prisma';
import { auth } from '../lib/auth';
import { createClient } from '@supabase/supabase-js';
import { Result } from '@cronjob/shared';

const router = Router();

// Middleware to check authentication
const requireAuth = async (req: any, res: any, next: any) => {
  const session = await auth.api.getSession({ headers: req.headers });
  if (!session) {
    return res.status(401).json(Result.fail('Unauthorized'));
  }
  req.user = session.user;
  next();
};

router.use(requireAuth);

// POST /api/cronjob/test-connection
router.post('/test-connection', async (req: any, res: any) => {
  try {
    const { configId } = req.body;

    const config = await prisma.supabaseConfig.findFirst({
      where: { id: configId, userId: req.user.id },
    });

    if (!config) {
      return res.status(404).json(Result.fail('Config not found'));
    }

    const supabase = createClient(config.supabaseUrl, config.supabaseServiceRoleKey);
    
    // Test connection by fetching 1 row from cronjob_keepalive
    const { data, error } = await supabase.from('cronjob_keepalive').select('*').limit(1);

    if (error) {
      if (error.code === '42P01') {
        // relation "cronjob_keepalive" does not exist
        await prisma.activityLog.create({
          data: { userId: req.user.id, configId: config.id, action: 'TEST', status: 'FAILED', message: 'Table not found' }
        });
        return res.status(400).json(Result.fail('Tabel cronjob_keepalive belum dibuat. Silakan klik Generate Table.'));
      }
      
      await prisma.activityLog.create({
        data: { userId: req.user.id, configId: config.id, action: 'TEST', status: 'FAILED', message: error.message }
      });
      return res.status(400).json(Result.fail(error.message));
    }

    await prisma.activityLog.create({
      data: { userId: req.user.id, configId: config.id, action: 'TEST', status: 'SUCCESS', message: 'Connection OK' }
    });
    return res.json(Result.ok({ success: true, message: 'Koneksi berhasil dan tabel ditemukan.' }));
  } catch (error: any) {
    return res.status(500).json(Result.fail(error.message));
  }
});

// POST /api/cronjob/ping
router.post('/ping', async (req: any, res: any) => {
  try {
    const { configId } = req.body;

    const config = await prisma.supabaseConfig.findFirst({
      where: { id: configId, userId: req.user.id },
    });

    if (!config) {
      return res.status(404).json(Result.fail('Config not found'));
    }

    const supabase = createClient(config.supabaseUrl, config.supabaseServiceRoleKey);
    
    // Insert ping
    const { error: insertError } = await supabase.from('cronjob_keepalive').insert([
      { source: 'CronJob Manager', message: 'Ping' }
    ]);

    if (insertError) {
      await prisma.activityLog.create({
        data: { userId: req.user.id, configId: config.id, action: 'PING', status: 'FAILED', message: insertError.message }
      });
      return res.status(400).json(Result.fail(`Gagal insert data: ${insertError.message}`));
    }

    await prisma.activityLog.create({
      data: { userId: req.user.id, configId: config.id, action: 'PING', status: 'SUCCESS' }
    });
    return res.json(Result.ok({ message: 'Ping berhasil. Data ditambahkan.' }));
  } catch (error: any) {
    return res.status(500).json(Result.fail(error.message));
  }
});

// POST /api/cronjob/generate-table
router.post('/generate-table', async (req: any, res: any) => {
  // Return the SQL string to the user
  const sql = `
CREATE TABLE cronjob_keepalive (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  source TEXT NOT NULL,
  message TEXT
);
ALTER TABLE cronjob_keepalive ENABLE ROW LEVEL SECURITY;
  `.trim();

  return res.json(Result.ok({ sql, message: 'Silakan jalankan SQL ini di menu SQL Editor Supabase Anda.' }));
});

export default router;
