/**
 * Utility to execute raw SQL on a remote Supabase database.
 *
 * Uses Supabase's internal pg-meta service endpoint (/pg/query)
 * which accepts the service_role key for authentication.
 * This allows DDL operations (CREATE TABLE, ALTER TABLE) that
 * are not supported by the standard PostgREST API (/rest/v1/).
 */

const MIGRATION_SQL = `
CREATE TABLE IF NOT EXISTS public.cronjob_keepalive (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  source TEXT NOT NULL,
  message TEXT
);

ALTER TABLE public.cronjob_keepalive ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE tablename = 'cronjob_keepalive' AND policyname = 'Allow all access'
  ) THEN
    CREATE POLICY "Allow all access" ON public.cronjob_keepalive FOR ALL USING (true) WITH CHECK (true);
  END IF;
END $$;

NOTIFY pgrst, 'reload schema';
`.trim();

export { MIGRATION_SQL };

export async function executeRemoteSQL(
  supabaseUrl: string,
  serviceRoleKey: string,
  sql: string
): Promise<{ success: boolean; data?: any; error?: string }> {
  try {
    // Use Supabase's pg-meta endpoint for DDL operations
    const response = await fetch(`${supabaseUrl}/pg/query`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'apikey': serviceRoleKey,
        'Authorization': `Bearer ${serviceRoleKey}`,
      },
      body: JSON.stringify({ query: sql }),
    });

    if (!response.ok) {
      const errorText = await response.text();
      return {
        success: false,
        error: `Remote SQL execution failed (HTTP ${response.status}): ${errorText}`,
      };
    }

    const result = await response.json().catch(() => ({}));
    return { success: true, data: result };
  } catch (error: any) {
    return {
      success: false,
      error: `Remote SQL connection error: ${error.message}`,
    };
  }
}

/**
 * Runs the standard cronjob_keepalive table migration on a remote
 * Supabase database and waits for PostgREST's schema cache to reload.
 */
export async function migrateKeepAliveTable(
  supabaseUrl: string,
  serviceRoleKey: string
): Promise<{ success: boolean; error?: string }> {
  const result = await executeRemoteSQL(supabaseUrl, serviceRoleKey, MIGRATION_SQL);

  if (!result.success) {
    return { success: false, error: result.error };
  }

  // Wait for PostgREST schema cache to reload after NOTIFY
  await new Promise((resolve) => setTimeout(resolve, 2000));

  return { success: true };
}
