/**
 * Utility to execute raw SQL on a remote Supabase database.
 *
 * Uses the `pg` (node-postgres) library to connect directly to
 * the Supabase PostgreSQL instance via `db.<ref>.supabase.co:5432`.
 * This allows DDL operations (CREATE TABLE, ALTER TABLE) that
 * are NOT supported by the Supabase REST/PostgREST API.
 *
 * Requires: the database password (found in Supabase Dashboard →
 *           Settings → Database → Connection info → Password).
 */

import pg from 'pg';

const { Client } = pg;

const MIGRATION_SQL = `
CREATE TABLE IF NOT EXISTS public.cronjob_keepalive (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  source TEXT NOT NULL,
  message TEXT
);

ALTER TABLE public.cronjob_keepalive ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE tablename = 'cronjob_keepalive' AND policyname = 'Allow all access'
  ) THEN
    EXECUTE 'CREATE POLICY "Allow all access" ON public.cronjob_keepalive FOR ALL USING (true) WITH CHECK (true)';
  END IF;
END $$;

-- Explicitly grant permissions so PostgREST API roles can access the table
GRANT USAGE ON SCHEMA public TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.cronjob_keepalive TO anon, authenticated, service_role;
GRANT ALL ON SEQUENCE public.cronjob_keepalive_id_seq TO anon, authenticated, service_role;

NOTIFY pgrst, 'reload schema';
`.trim();

export { MIGRATION_SQL };

/**
 * Extract the project reference from a Supabase URL.
 * e.g. "https://uwhqwobgvwhkgddoowzz.supabase.co" → "uwhqwobgvwhkgddoowzz"
 */
function extractRef(supabaseUrl: string): string {
  const match = supabaseUrl.match(/https:\/\/([a-z0-9]+)\.supabase\.co/);
  if (!match) throw new Error(`Cannot extract project ref from URL: ${supabaseUrl}`);
  return match[1];
}

export async function executeRemoteSQL(
  supabaseUrl: string,
  databasePassword: string,
  sql: string,
  poolerUrl?: string | null
): Promise<{ success: boolean; data?: any; error?: string }> {
  const ref = extractRef(supabaseUrl);

  let host = `db.${ref}.supabase.co`;
  let port = 5432;
  let user = 'postgres';

  if (poolerUrl) {
    try {
      // Allow user to provide a full URL or just the host.
      // If they provide host like aws-0-ap-southeast-1.pooler.supabase.com
      if (!poolerUrl.includes('://')) {
        host = poolerUrl;
        user = `postgres.${ref}`;
      } else {
        const parsed = new URL(poolerUrl);
        host = parsed.hostname;
        port = parseInt(parsed.port) || 5432;
        user = parsed.username || `postgres.${ref}`;
      }
    } catch (e) {
      // Fallback
    }
  }

  const client = new Client({
    host,
    port,
    database: 'postgres',
    user,
    password: databasePassword,
    ssl: { rejectUnauthorized: false },
    connectionTimeoutMillis: 10000,
  });

  try {
    await client.connect();
    const result = await client.query(sql);
    return { success: true, data: result };
  } catch (error: any) {
    return {
      success: false,
      error: `Remote SQL error: ${error.message}`,
    };
  } finally {
    await client.end().catch(() => {}); // always close
  }
}

/**
 * Runs the standard cronjob_keepalive table migration on a remote
 * Supabase database and waits for PostgREST's schema cache to reload.
 */
export async function migrateKeepAliveTable(
  supabaseUrl: string,
  databasePassword: string,
  poolerUrl?: string | null
): Promise<{ success: boolean; error?: string }> {
  const result = await executeRemoteSQL(supabaseUrl, databasePassword, MIGRATION_SQL, poolerUrl);

  if (!result.success) {
    return { success: false, error: result.error };
  }

  // Wait for PostgREST schema cache to reload after NOTIFY
  await new Promise((resolve) => setTimeout(resolve, 2000));

  return { success: true };
}
